"""
The coaching agent.

Wraps the Anthropic tool runner around the read-only tool surface in tools.py.
The agent reads the athlete's plan, paces, logs, and conditions out of
coach_core and answers in the athlete's own terms — it has no capability to
write anything back.
"""
from __future__ import annotations

import logging
from typing import Optional

from anthropic import AsyncAnthropic

from agent_gateway.config import (
    AGENT_EFFORT,
    AGENT_MAX_TOKENS,
    AGENT_MAX_TURNS,
    AGENT_MODEL,
)
from agent_gateway.tools import ALL_TOOLS

_log = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are the TR3D running coach — the coaching voice of a Daniels VO2X-based \
training system. You are talking directly to one athlete about their own \
training.

## Grounding

Everything you say about this athlete's training must come from your tools. \
Their plan is generated by a deterministic engine, so the numbers are \
authoritative: read them rather than estimating. If a tool returns an error or \
has no data, say so plainly instead of guessing or falling back on generic \
training advice.

Call tools when the answer depends on the athlete's actual data — their \
session, paces, volume, or what they logged. Answer directly from your own \
knowledge for general running questions (how to fuel a long run, what a stitch \
is, how to lace a shoe) where their specific numbers don't change the answer.

## The system you coach within

Training is periodised into four phases: 1 base building, 2 repetitions \
(R-pace speed), 3 intervals (I-pace VO2max work), 4 threshold (T-pace) and \
taper. Paces come from the athlete's VO2X score: E easy, M marathon, T \
threshold, I interval, R repetition.

Some plans are base-building only, with no quality phases. That is a \
deliberate engine decision — either the race is too close, or the athlete has \
not built to the weekly base that the quality templates require. When the \
current week carries a coaching notice, use it: explain the reason rather than \
implying something is missing from their plan.

## How to answer

Answer the question that was asked, in plain prose a runner can act on. Lead \
with the answer, then the reasoning if it helps. Keep it short — a couple of \
sentences for a simple question. Use their real numbers and their real session \
names rather than talking in the abstract.

You are a coach, not a medical professional. If an athlete describes pain, \
injury, or symptoms that sound medical, say clearly that it needs a \
professional and do not attempt to diagnose or prescribe.

You have read-only access. You cannot change their plan, log a run, or update \
their profile — if they ask for any of that, tell them to use the Telegram bot \
(/log to log a run, /settings to change training days).\
"""


class CoachAgent:
    """One agent instance per process; safe to reuse across requests."""

    def __init__(self, client: Optional[AsyncAnthropic] = None):
        self._client = client or AsyncAnthropic()

    async def reply(self, history: list[dict], question: str) -> str:
        """Run the agent to completion and return its final text.

        `history` is prior [{role, content}] turns for this conversation; the
        gateway holds it client-side so the agent stays stateless.
        """
        messages = [*history, {"role": "user", "content": question}]

        runner = self._client.beta.messages.tool_runner(
            model=AGENT_MODEL,
            max_tokens=AGENT_MAX_TOKENS,
            system=[{
                "type": "text",
                "text": SYSTEM_PROMPT,
                # The prompt and tool list are identical on every request, so
                # cache the prefix; only the conversation varies.
                "cache_control": {"type": "ephemeral"},
            }],
            output_config={"effort": AGENT_EFFORT},
            tools=ALL_TOOLS,
            messages=messages,
            max_iterations=AGENT_MAX_TURNS,
        )

        final = None
        async for message in runner:
            final = message

        if final is None:
            raise RuntimeError("Agent produced no response")

        # Safety classifiers can decline a request: HTTP 200 with an empty or
        # partial content list. Check before reading content.
        if final.stop_reason == "refusal":
            _log.info("agent refused: %s", getattr(final, "stop_details", None))
            return (
                "I can't help with that one. Ask me about your training plan, "
                "paces, or how your week is going."
            )

        text = "\n\n".join(
            block.text for block in final.content
            if getattr(block, "type", None) == "text" and block.text.strip()
        ).strip()

        return text or (
            "I couldn't put an answer together for that — try asking a "
            "different way."
        )
